name: release-please

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      core_release_created: ${{ steps.rp_core.outputs['packages/core--release_created'] }}
      front_release_created: ${{ steps.rp_front.outputs['packages/front--release_created'] }}

    steps:
      - name: Release Please (core)
        uses: googleapis/release-please-action@v4
        id: rp_core
        with:
          release-type: node
          path: packages/core
          include-component-in-tag: true

      - name: Release Please (front)
        uses: googleapis/release-please-action@v4
        id: rp_front
        with:
          release-type: node
          path: packages/front
          include-component-in-tag: true

  publish:
    needs: release
    if: ${{ needs.release.outputs.core_release_created == 'true' || needs.release.outputs.front_release_created == 'true' }}
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/publish-npm.yml
    with:
      publish_core: ${{ needs.release.outputs.core_release_created == 'true' }}
      publish_front: ${{ needs.release.outputs.front_release_created == 'true' }}
